apiVersion: v1
kind: Service
metadata:
  name: destiny-core-flowauth-service
  namespace: destinycore-flow
spec:
  type: NodePort
  selector:
    app: destiny-core-flowauth-pod
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30201
